### ISSUE TITLE
Change windows `CMAKE_INSTALL_PREFIX` from `%LIBRARY_PREFIX%` to `%PREFIX%`

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/xtensor-feedstock#39]
Most other recipes based on cmake on conda-forge use `%LIBRARY_PREFIX%` and we have been respecting that pattern in xtensor, but I wonder what is the point of this convention, which differs from Unix where we use `CMAKE_INSTALL_PREFIX=$PREFIX`.

**Comment by SylvainCorlay** [comment]
cc @jakirkham

**Comment by SylvainCorlay** [comment]
cf https://github.com/QuantStack/xtensor/pull/319

The `%PREFIX%` directory should coincide with `sys.prefix` but I don't know if `%LIBRARY_PREFIX%` is a addressable from python.

**Comment by tdegeus** [comment]
Thanks to @ndevenish I stumbled on this, deriving from the following question I posed on gitter: 

On my windows CI, conda installs a header only library under `C:\Users\runneradmin\micromamba\envs\myenv\Library\include\xtensor`. My question, why is there Library in the path?

The problem is that it impedes me to overwrite it manually, as installing using CMake configured as `cmake -Bbuild -DCMAKE_INSTALL_PREFIX:PATH="${CONDA_PREFIX}"` installs in `C:\Users\runneradmin\micromamba\envs\myenv\include\xtensor` (i.e. the path without the Library, that is somehow given a lower priority when building my actual code)

@SylvainCorlay @wolfv @JohanMabille
